export default Object.freeze({
    index: "/",
    Login: "/Login/",
    Wallet: "/Wallet/",
    Dashboard: "/test/",
    Success: "/Success/",
    Buy: "/teacher/buy/",
    Earnings: "/Earning/",
    Widthraw: "/widthraw/",
    AddTest: "/teacher/addtest/",
    Marketplace: "/Marketplace/",
    TeacherDashboard: "/teacher/",
    Allocate: "/teacher/allocate/",
    TeacherSuccess: "/teacher/success/",
    WidthrawSuccess: "/widthraw/success/",
})